trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
  - script: |
      set -ex

      pushd process-template-files
        npm install
        npm run test
        rm -rf node_modules
        npm install --production
      popd
    displayName: Test All Custom Tasks

  - script: |
      set -ex
      sudo npm install -g tfx-cli@0.7.11

      tfx extension publish \
        --no-prompt \
        --manifest-globs vss-extension.json \
        --override "{ \"version\": \"1.0.${BUILD_BUILDID}\" }" \
        --share-with codexarcana \
        --token $(PAT)
    displayName: Publish Extension

  - script: |
      set -ex
      az extension add --name azure-devops

      echo "$(PAT)" | az devops login --organization https://dev.azure.com/codexarcana/

      set +e

      az devops extension install \
        --organization https://dev.azure.com/codexarcana \
        --publisher-id codexarcana \
        --extension-id codexarcana-pipeline-tasks || true
    displayName: Install Extension To Codex Arcana
