trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
  - script: |
      set -ex
      pushd buildAndReleaseTask
        npm install
        npm run test
      popd

      npm install -g tfx-cli@0.7.11

      tfx extension publish \
        --no-prompt \
        --manifest-globs vss-extension.json \
        --override "{ \"version\": \"0.0.${Build.BuildId}\"  }" \
        --share-with codexarcana \
        --token $(PAT)