trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
  - script: |
      set -ex
      
      env

      pushd buildAndReleaseTask
        npm install
        npm run test
      popd

      sudo npm install -g tfx-cli@0.7.11

      tfx extension publish \
        --no-prompt \
        --manifest-globs vss-extension.json \
        --override "{ \"version\": \"1.0.${BUILD_BUILDID}\" }" \
        --share-with codexarcana \
        --token $(PAT)